#!/usr/bin/env python3
"""
LoRA online validation gate.

Inputs are quality reports generated by scripts/run_quality_eval.py for base
and LoRA services. The gate compares pass rate, category deltas, latency, and
an optional general-capability regression set to detect catastrophic forgetting.
"""

from __future__ import annotations

import argparse
import json
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, Iterable, List, Tuple


def load_report(path: Path) -> Dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def category_rates(report: Dict[str, Any]) -> Dict[str, float]:
    out: Dict[str, float] = {}
    for cat, stat in report.get("summary", {}).get("by_category", {}).items():
        total = int(stat.get("total", 0))
        passed = int(stat.get("passed", 0))
        out[cat] = round(passed / total, 6) if total else 0.0
    return out


def pass_rate(report: Dict[str, Any]) -> float:
    return float(report.get("summary", {}).get("pass_rate", 0.0))


def latency_avg(report: Dict[str, Any]) -> int:
    return int(report.get("summary", {}).get("latency_ms", {}).get("avg", 0))


def compare_categories(base: Dict[str, float], lora: Dict[str, float]) -> List[Dict[str, Any]]:
    rows: List[Dict[str, Any]] = []
    for cat in sorted(set(base) | set(lora)):
        b = base.get(cat, 0.0)
        l = lora.get(cat, 0.0)
        rows.append({"category": cat, "base": b, "lora": l, "delta": round(l - b, 6)})
    return rows


def collect_failed_cases(report: Dict[str, Any], limit: int = 20) -> List[Dict[str, Any]]:
    rows = []
    for item in report.get("results", []):
        if not item.get("passed"):
            rows.append(
                {
                    "id": item.get("id"),
                    "category": item.get("category"),
                    "query": item.get("query"),
                    "reasons": item.get("reasons", []),
                    "answer_preview": item.get("answer_preview", ""),
                }
            )
        if len(rows) >= limit:
            break
    return rows


def to_markdown(gate: Dict[str, Any]) -> str:
    lines = [
        "# MiniCPM-V LoRA 上线验证门禁",
        "",
        f"- 生成时间：{gate['created_at']}",
        f"- 决策：**{gate['decision']}**",
        f"- base report：`{gate['base_report']}`",
        f"- lora report：`{gate['lora_report']}`",
        "",
        "## 总体指标",
        "",
        "| 指标 | base | lora | delta | 阈值 |",
        "|---|---:|---:|---:|---:|",
        (
            f"| pass_rate | {gate['base_pass_rate']:.4f} | {gate['lora_pass_rate']:.4f} | "
            f"{gate['delta_pass_rate']:+.4f} | >= {gate['thresholds']['min_pass_delta']:.4f} |"
        ),
        (
            f"| avg_latency_ms | {gate['base_latency_ms']} | {gate['lora_latency_ms']} | "
            f"{gate['latency_delta_ms']:+d} | <= {gate['thresholds']['max_latency_delta_ms']} |"
        ),
        "",
        "## 分类指标",
        "",
        "| category | base | lora | delta |",
        "|---|---:|---:|---:|",
    ]
    for row in gate["category_deltas"]:
        lines.append(f"| {row['category']} | {row['base']:.4f} | {row['lora']:.4f} | {row['delta']:+.4f} |")
    if gate.get("general_capability"):
        gen = gate["general_capability"]
        lines.extend(
            [
                "",
                "## 通用能力回归",
                "",
                "| 指标 | base | lora | drop | 阈值 |",
                "|---|---:|---:|---:|---:|",
                (
                    f"| general_pass_rate | {gen['base_pass_rate']:.4f} | {gen['lora_pass_rate']:.4f} | "
                    f"{gen['drop']:+.4f} | >= -{gate['thresholds']['max_general_drop']:.4f} |"
                ),
            ]
        )
    lines.extend(["", "## 门禁原因", ""])
    for reason in gate["reasons"]:
        lines.append(f"- {reason}")
    if gate["lora_failed_cases"]:
        lines.extend(["", "## LoRA 失败样本 TopN", ""])
        for case in gate["lora_failed_cases"]:
            lines.append(f"- `{case['id']}` [{case['category']}] {case['query']}：{'; '.join(case['reasons'])}")
    lines.extend(
        [
            "",
            "## 面试回答提示",
            "",
            "- 如果 LoRA pass_rate 提升且通用集下降低于阈值，可以进入灰度或 shadow 验证。",
            "- 如果领域集提升但通用集明显下降，优先判断灾难性遗忘，回退 rank/学习率或混入通用 replay 样本。",
            "- 如果训练集 loss 降但门禁不通过，不能上线 adapter，只保留为实验记录。",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description="Validate LoRA release with base/lora quality reports")
    ap.add_argument("--base-report", required=True)
    ap.add_argument("--lora-report", required=True)
    ap.add_argument("--general-base-report", default="", help="optional general capability base report")
    ap.add_argument("--general-lora-report", default="", help="optional general capability lora report")
    ap.add_argument("--min-pass-delta", type=float, default=0.0)
    ap.add_argument("--max-general-drop", type=float, default=0.02)
    ap.add_argument("--max-latency-delta-ms", type=int, default=800)
    ap.add_argument("--output-json", default="")
    ap.add_argument("--output-md", default="")
    args = ap.parse_args()

    base_path = Path(args.base_report).resolve()
    lora_path = Path(args.lora_report).resolve()
    base = load_report(base_path)
    lora = load_report(lora_path)

    base_rate = pass_rate(base)
    lora_rate = pass_rate(lora)
    delta = round(lora_rate - base_rate, 6)
    base_latency = latency_avg(base)
    lora_latency = latency_avg(lora)
    latency_delta = lora_latency - base_latency
    reasons: List[str] = []

    if delta >= args.min_pass_delta:
        reasons.append(f"领域质量通过：pass_rate delta={delta:+.4f}")
    else:
        reasons.append(f"领域质量未达标：pass_rate delta={delta:+.4f} < {args.min_pass_delta:.4f}")

    if latency_delta <= args.max_latency_delta_ms:
        reasons.append(f"延迟通过：avg latency delta={latency_delta:+d}ms")
    else:
        reasons.append(f"延迟未达标：avg latency delta={latency_delta:+d}ms > {args.max_latency_delta_ms}ms")

    general_payload = None
    general_ok = True
    if args.general_base_report and args.general_lora_report:
        gb_path = Path(args.general_base_report).resolve()
        gl_path = Path(args.general_lora_report).resolve()
        gb = load_report(gb_path)
        gl = load_report(gl_path)
        gb_rate = pass_rate(gb)
        gl_rate = pass_rate(gl)
        drop = round(gl_rate - gb_rate, 6)
        general_ok = drop >= -args.max_general_drop
        general_payload = {
            "base_report": str(gb_path),
            "lora_report": str(gl_path),
            "base_pass_rate": gb_rate,
            "lora_pass_rate": gl_rate,
            "drop": drop,
        }
        if general_ok:
            reasons.append(f"通用能力回归通过：general delta={drop:+.4f}")
        else:
            reasons.append(f"通用能力回归未达标：general delta={drop:+.4f} < -{args.max_general_drop:.4f}")
    else:
        reasons.append("未提供通用能力回归报告，无法自动判断灾难性遗忘。")

    decision = "PASS" if delta >= args.min_pass_delta and latency_delta <= args.max_latency_delta_ms and general_ok else "BLOCK"
    gate = {
        "created_at": datetime.now().isoformat(timespec="seconds"),
        "decision": decision,
        "base_report": str(base_path),
        "lora_report": str(lora_path),
        "base_pass_rate": base_rate,
        "lora_pass_rate": lora_rate,
        "delta_pass_rate": delta,
        "base_latency_ms": base_latency,
        "lora_latency_ms": lora_latency,
        "latency_delta_ms": latency_delta,
        "category_deltas": compare_categories(category_rates(base), category_rates(lora)),
        "general_capability": general_payload,
        "thresholds": {
            "min_pass_delta": args.min_pass_delta,
            "max_general_drop": args.max_general_drop,
            "max_latency_delta_ms": args.max_latency_delta_ms,
        },
        "reasons": reasons,
        "lora_failed_cases": collect_failed_cases(lora),
    }

    default_dir = lora_path.parent
    out_json = Path(args.output_json).resolve() if args.output_json else default_dir / "lora_release_gate.json"
    out_md = Path(args.output_md).resolve() if args.output_md else default_dir / "lora_release_gate.md"
    out_json.parent.mkdir(parents=True, exist_ok=True)
    out_md.parent.mkdir(parents=True, exist_ok=True)
    out_json.write_text(json.dumps(gate, ensure_ascii=False, indent=2), encoding="utf-8")
    out_md.write_text(to_markdown(gate), encoding="utf-8")
    print(f"decision={decision}")
    print(f"gate_json={out_json}")
    print(f"gate_md={out_md}")
    return 0 if decision == "PASS" else 1


if __name__ == "__main__":
    raise SystemExit(main())
