#!/usr/bin/env bash
# MiniCPM-V LoRA 流水线：数据准备 ->（可选）训练 -> 评测对比 -> 汇总报告
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"

MODE="${1:-eval-only}" # eval-only | train-and-eval
EXPERIMENT_ID="${EXPERIMENT_ID:-minicpm-v26-lora-$(date +%Y%m%d-%H%M%S)}"
LORA_OUT_DIR="${LORA_OUT_DIR:-artifacts/lora/${EXPERIMENT_ID}}"

BASE_URL="${BASE_URL:-http://127.0.0.1:8000}"
LORA_URL="${LORA_URL:-http://127.0.0.1:8010}"
MIN_DELTA="${MIN_DELTA:-0.00}"
COMPARE_OUT_DIR="${COMPARE_OUT_DIR:-logs/lora_eval/${EXPERIMENT_ID}}"
STRICT_GATE="${STRICT_GATE:-1}"

if [[ "$MODE" != "eval-only" && "$MODE" != "train-and-eval" ]]; then
  echo "[lora-pipeline] invalid mode: $MODE (expected eval-only | train-and-eval)" >&2
  exit 2
fi

echo "[lora-pipeline] experiment_id=$EXPERIMENT_ID mode=$MODE"

python scripts/lora/prepare_sft_data.py \
  --pages data/user_pages.json \
  --quality data/rag_quality_testset.json \
  --output-train data/lora/train.jsonl \
  --output-val data/lora/val.jsonl

if [[ "$MODE" == "train-and-eval" ]]; then
  echo "[lora-pipeline] training..."
  python scripts/lora/train_minicpm_lora.py --config configs/lora/minicpm_v26_qlora.yaml
  if [[ -d "artifacts/lora/minicpm-v26-domain-v1" ]]; then
    mkdir -p "$LORA_OUT_DIR"
    cp -R artifacts/lora/minicpm-v26-domain-v1/. "$LORA_OUT_DIR/"
  fi
  python - <<'PY'
import json
from datetime import datetime
from pathlib import Path
exp = Path("artifacts/lora")
exp.mkdir(parents=True, exist_ok=True)
meta = {
    "created_at": datetime.now().isoformat(timespec="seconds"),
    "adapter_note": "Generated by run_minicpm_lora_pipeline.sh",
}
Path("artifacts/lora/latest_adapter_meta.json").write_text(json.dumps(meta, ensure_ascii=False, indent=2), encoding="utf-8")
print("adapter_meta=artifacts/lora/latest_adapter_meta.json")
PY
fi

echo "[lora-pipeline] running eval compare..."
python scripts/lora/eval_lora_checkpoint.py \
  --base-url "$BASE_URL" \
  --lora-url "$LORA_URL" \
  --out-dir "$COMPARE_OUT_DIR"

gate_rc=0
python scripts/lora/lora_release_gate.py \
  --base-report "$COMPARE_OUT_DIR/base_report.json" \
  --lora-report "$COMPARE_OUT_DIR/lora_report.json" \
  --min-pass-delta "$MIN_DELTA" \
  --output-json "$COMPARE_OUT_DIR/lora_release_gate.json" \
  --output-md "$COMPARE_OUT_DIR/lora_release_gate.md" || gate_rc=$?

python scripts/lora/summarize_lora_eval.py \
  --compare "$COMPARE_OUT_DIR/compare_summary.json" \
  --experiment-id "$EXPERIMENT_ID" \
  --base-url "$BASE_URL" \
  --lora-url "$LORA_URL" \
  --min-delta "$MIN_DELTA" \
  --note "LoRA pipeline auto summary"

if [[ "$STRICT_GATE" == "1" && "$gate_rc" != "0" ]]; then
  echo "[lora-pipeline] release gate blocked; reports kept under $COMPARE_OUT_DIR" >&2
  exit "$gate_rc"
fi

echo "[lora-pipeline] done"
